In [51]:
from IPython.display import YouTubeVideo
YouTubeVideo("M_eYSuPKP3Y",width="640",height="390")

<pre>











</pre>

<img src="https://raw.githubusercontent.com/profjsb/python-bootcamp/master/Lectures/02_AdvancedDataStructures/slide1.png" width="90%">
UC Berkeley Python Bootcamp (c) J. Bloom All Rights Reserved

## There are four main types of collections of data ("Sequence objects") ##

	•	Lists: a mutable array of data
	•	Tuples: ordered, immutable list
	•	Sets: unordered collection of unique elements
	•	Dictionaries: keyword/value lookup

The value in each element can be whatever (type) you want.
> string is actually a sequence object

### Tuple ###
denoted with parentheses

In [1]:
t = (12,-1)
print(type(t))

<class 'tuple'>


In [4]:
print(isinstance(t,tuple))
print(len(t))

True
2


In [9]:
t = (12,"monty",True,-1.23e6)
print(t[1])

monty


In [10]:
print(t[-1])

-1230000.0


In [21]:
t

(12, 'monty', True, -1230000.0)

In [38]:
t[-2:]  # get the last two elements, return as a tuple

(True, -1230000.0)

In [39]:
x = (True) ; print(type(x))
x = (True,) ; print(type(x))

<class 'bool'>
<class 'tuple'>


In [40]:
type(()), len(())

(tuple, 0)

In [41]:
type((,))

SyntaxError: invalid syntax (<ipython-input-41-ff592953e249>, line 1)

single-element tuples look like `(element,)`

cannot change a tuple
but you can create new one with concatenation

In [43]:
t[2] = False

TypeError: 'tuple' object does not support item assignment

In [45]:
type((1,"spam","eggs", None))

tuple

In [46]:
t[0:2], False, t[3:]

((12, 'monty'), False, (-1230000.0,))

In [47]:
## the above it 
## not what we wanted... need to concatenate
t[0:2] + False + t[3:]

TypeError: can only concatenate tuple (not "bool") to tuple

In [48]:
y = t[0:2] + (False,) + t[3:] ; print(y)

(12, 'monty', False, -1230000.0)


In [49]:
t*2

(12, 'monty', True, -1230000.0, 12, 'monty', True, -1230000.0)

In [50]:
t.__rmul__(2)

(12, 'monty', True, -1230000.0, 12, 'monty', True, -1230000.0)

&nbsp;

### List ###
#### denoted with a brackets ####

In [52]:
v = [1,2,3] ; print(len(v), type(v))

3 <class 'list'>


In [53]:
v[0:2]

[1, 2]

In [54]:
v = ["eggs","spam",-1,("monty","python"),[-1.2,-3.5]]
len(v)

5

In [55]:
v[0] ="green egg"
v[1] += ",love it."
v[-1]

[-1.2, -3.5]

In [57]:
v

['green egg', 'spam,love it.', -1, ('monty', 'python'), [-1.2, -3.5]]

In [58]:
v[-1][1]

-3.5

In [59]:
v[-1][1] = None ; print(v)

['green egg', 'spam,love it.', -1, ('monty', 'python'), [-1.2, None]]


In [60]:
v = v[2:] ; print(v)

[-1, ('monty', 'python'), [-1.2, None]]


In [61]:
# let's make a proto-array out of nested lists
vv = [ [1,2], [3,4] ]

In [100]:
print(len(vv))

2


In [101]:
vv

[[1, 2], [3, 4]]

In [114]:
det = vv[0][0]*vv[1][1] - vv[0][1]*vv[1][0] ; print(det)

-2


In [115]:
determinant = vv[0][0]*vv[1][1] - vv[0][1]*vv[1][0]
print(determinant)

-2


the main point here: lists are **changeable** ("mutable")

In [141]:
import numpy as np


mat = np.arange(6*6).reshape(6, 6) ; print(mat)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [142]:
det = np.linalg.det(mat) ; 
print(f"Determinant of the matrix: {det}")

Determinant of the matrix: 0.0


### lists can be extended & appended ###

In [143]:
v = [1,2,3]z
v.append(4)   
print(v)

SyntaxError: invalid syntax (<ipython-input-143-f564322b2896>, line 1)

> Lists can be considered objects.
**Objects** are like animals: they know how to do stuff (like eat and sleep), they know how to interact with others (like make children), and they have characteristics (like height, weight).

> "Knowing how to do stuff" with itself is called a method. In this case "append" is a method which, when invoked, is an action that changes the characteristics (the data vector of the list itself).

### List ###
#### lists can be extended, appended, and popped ####

In [144]:
v = [1,2,3]
v.append(4)
v.append([-5]) ; print(v)

[1, 2, 3, 4, [-5]]


In [145]:
v = v[:4]
w = ['elderberries', 'eggs']
v + w

[1, 2, 3, 4, 'elderberries', 'eggs']

In [146]:
v.extend(w) ; print(v)

[1, 2, 3, 4, 'elderberries', 'eggs']


In [148]:
v.pop()

'elderberries'

In [149]:
print(v)

[1, 2, 3, 4]


In [150]:
v.pop(0) ; print(v) ## pop the first element

[2, 3, 4]


In [151]:
v.append(0)

In [152]:
v = ["hello"] + v

In [153]:
print(v)

['hello', 2, 3, 4, 0]


 * `.append()`: adds a new element
 * `.extend()`: concatenates a list/element
 * `.pop()`: remove an element

#### lists can be searched, sorted, & counted ####

In [155]:
v = [1,3, 2, 3, 4, 1.3]
v.sort() ; print(v)

[1, 1.3, 2, 3, 3, 4]


If there isn't a natural way to compare elements, the sort will fail.

`reverse` is a keyword of the `.sort()` method

In [167]:
import math
v = [1,3, 2, 3, 4, math.pi]
v.sort() ; print(v)

[1, 2, 3, 3, 3.141592653589793, 4]


In [168]:
v.sort(reverse=True) ; print(v)

[4, 3.141592653589793, 3, 3, 2, 1]


In [169]:
v.sort?

Signature: v.sort(*, key=None, reverse=False)
Docstring:
Sort the list in ascending order and return None.

The sort is in-place (i.e. the list itself is modified) and stable (i.e. the
order of two equal elements is maintained).

If a key function is given, apply it once to each list item and sort them,
ascending or descending, according to their function values.

The reverse flag can be set to sort in descending order.
Type:      builtin_function_or_method


`.sort()` changes the the list in place 

In [170]:
v.index(4)   ## lookup the index of the entry 4

0

In [171]:
v.index(3)

2

In [172]:
v.count(3)

2

In [174]:
v.insert(0,"it's full of stars") ; print(v)

["it's full of stars", "it's full of stars", 4, 3.141592653589793, 3, 3, 2, 1]


In [181]:
v.insert(-1, "righty tighty") ; print(v)

["it's full of stars", "it's full of stars", 4, 3.141592653589793, 3, 2, 'righty tighty', 1]


In [182]:
v.remove("righty tighty") ; print(v)

["it's full of stars", "it's full of stars", 4, 3.141592653589793, 3, 2, 1]


 &nbsp;

### IPython is your new best friend ##

1. Type `v.` then the Tab button

2. Type `v.re` then the Tab button

3. Type `v.remove?`

In [183]:
## try it here

In [200]:
v.insert(0, "righty tighty") ; print(v)

['righty tighty', "it's full of stars", "it's full of stars", 4, 3.141592653589793, 2, 1, "it's full of stars", "it's full of stars", 4, 3.141592653589793, 3, 2, 1, 3]


In [201]:
v

['righty tighty',
 "it's full of stars",
 "it's full of stars",
 4,
 3.141592653589793,
 2,
 1,
 "it's full of stars",
 "it's full of stars",
 4,
 3.141592653589793,
 3,
 2,
 1,
 3]

 &nbsp;

### List ###
#### iteration ####

In [204]:
x = 1
a = ['cat', 'window', 'defenestrate']
for x in a:
    print(x, len(x))
    if x == "cat":
        a.append("?")
print(x)
print(a)

cat 3
window 6
defenestrate 12
? 1
?
['cat', 'window', 'defenestrate', '?']


In [208]:
for i, x in enumerate(a): # loops over a and returns a tuple with the index and the value
    print(i, x, len(x))     # i is the where we are in the list, x is the value.

0 cat 3
1 window 6
2 defenestrate 12
3 ? 1


In [206]:
for i, x in enumerate(a):
       print(i, x, len(x))

0 cat 3
1 window 6
2 defenestrate 12
3 ? 1


In [250]:
b = enumerate(a)

In [252]:
b

In [253]:
print(b), ; type(b)

enumerate

In [239]:
print(b.__next__())

(3, '?')


In [236]:
for i in range(3):
    print(b.__next__())

(0, 'cat')
(1, 'window')
(2, 'defenestrate')


In [237]:
for x in a:
       print(x, end=',')

cat,window,defenestrate,?,

The syntax for iteration is...  

    for variable_name in iterable:
       # do something with variable_name

The `range()` function

In [259]:
x = list(range(4)) ; print(x)
total = 0
for val in range(4):
        total += val
        print("By adding " + str(val) + \
              " the total is now " + str(total))

[0, 1, 2, 3]
By adding 0 the total is now 0
By adding 1 the total is now 1
By adding 2 the total is now 3
By adding 3 the total is now 6



`range`([`start`,] `stop`[, `step`])
→ list of integers

In [264]:
total = 0
for x in range(1,15,2):
    print(x)
    total += x
    print("By adding " + str(x) + \
          " the total is now " + str(total))

1
By adding 1 the total is now 1
3
By adding 3 the total is now 4
5
By adding 5 the total is now 9
7
By adding 7 the total is now 16
9
By adding 9 the total is now 25
11
By adding 11 the total is now 36
13
By adding 13 the total is now 49


In [267]:
a = ['Mary', 'had', 'a', 'little', 'lamb']
for i in range(len(a)):
    print(i, a[i])

0 Mary
1 had
2 a
3 little
4 lamb


In [268]:
for index, item in enumerate(a):
    print(index, item)

0 Mary
1 had
2 a
3 little
4 lamb


 &nbsp;

### Sets ###
#### denoted with a curly braces ####

In [269]:
{1,2,3,"bingo"}

{1, 2, 3, 'bingo'}

In [270]:
print(type({1,2,3,"bingo"}))

<class 'set'>


In [271]:
print(type({}))

<class 'dict'>


In [272]:
print(type(set()))

<class 'set'>


In [277]:
set(["spamIam"])

{'spamIam'}

In [278]:
type(set(["spamIam"]))

set

In [293]:
set("spamIam")

{'I', 'a', 'm', 'p', 's'}

In [313]:
type(set("spamIam"))

set

sets have unique elements. They can be
compared, differenced, unionized, etc.

In [314]:
a = set("sp") ; b = set("am"); print(a) ; print(b)

{'s', 'p'}
{'m', 'a'}


In [315]:
b

{'a', 'm'}

In [316]:
c = set(["m","a"])
c == b

True

In [317]:
c

{'a', 'm'}

In [318]:
a

{'p', 's'}

In [319]:
"p" in a

True

In [320]:
"ps" in a

False

In [321]:
q = set("spamIam")
a.issubset(q)

True

In [322]:
a | b

{'a', 'm', 'p', 's'}

In [324]:
q - (a | b)

{'I'}

In [325]:
q & (a | b)

{'a', 'm', 'p', 's'}

Like lists, we can use as (unordered) buckets
`.pop()` gives us a random element

In [326]:
# this is pretty volitile...wont be the same
# order on all machines
for i in q & (a | b):
    print(i, end=' ') 

m s p a 

In [327]:
q.remove("a")

In [328]:
q.pop()

'p'

In [329]:
print(q.pop())
print(q.pop())

I
s


In [330]:
print(q.pop())


m


In [331]:
print(q)

set()


In [332]:
q.pop()

KeyError: 'pop from an empty set'

 &nbsp;

## Dictionaries ##
denoted with a curly braces and colons

In [333]:
d = {"favorite cat": None, "favorite spam": "all"}

these are key: value, key: value, ...

In [335]:
print(d["favorite cat"])
d[0]   ## this is not a list and you dont have a keyword = 0

None


KeyError: 0

In [337]:
e = {"favorite cat": None, "favorite spam": "all", \
     1: 'loneliest number'}
e[1] == 'loneliest number'

True

dictionaries are **UNORDERED**<sup>*</sup>.  
>You cannot assume that one key comes before or after another

<sup>*</sup> you can use a special type of ordered dict if you really need it:

https://docs.python.org/3.1/whatsnew/3.1.html#pep-372-ordered-dictionaries

### 4 ways to make a Dictionary ###

In [338]:
# number 1...you've seen this
d = {"favorite cat": None, "favorite spam": "all"}

In [339]:
# number 2
d = dict(one = 1, two=2,cat = 'dog') ; print(d)

{'one': 1, 'two': 2, 'cat': 'dog'}


In [340]:
# number 3 ... just start filling in items/keys
d = {}  # empty dictionary
d['cat'] = 'dog'
d['one'] = 1
d['two'] = 2
d

{'cat': 'dog', 'one': 1, 'two': 2}

In [341]:
# number 4... start with a list of tuples
mylist = [("cat","dog"), ("one",1),("two",2)]
print(dict(mylist))

{'cat': 'dog', 'one': 1, 'two': 2}


In [342]:
dict(mylist) == d

True

In [343]:
list(d)

['cat', 'one', 'two']

 &nbsp;

#### Dictionaries: they can be complicated (in a good way) ####

In [344]:
d = {"favorite cat": None, "favorite spam": "all"}

In [347]:
d = {'favorites': {'cat': None, 'spam': 'all'}, \
     'least favorite': {'cat': 'all', 'spam': None}}
print(d['least favorite']['cat'])

all


remember: the backslash (\) allows you to across break lines. Not technically needed when defining a dictionary or list

In [364]:
phone_numbers = {'family': [('mom','642-2322'),('dad','534-2311')],\
                     'friends': [('Billy','652-2212')]}

In [365]:
for group_type in ['friends','family']:
        print("Group",group_type,":",sep=" ")
        for info in phone_numbers[group_type]:
             print("\t",info[0],info[1],sep=" ")

Group friends :
	 Billy 652-2212
Group family :
	 mom 642-2322
	 dad 534-2311


In [366]:
# this will return a list, but you dont know in what order! 
list(phone_numbers.keys())

['family', 'friends']

In [367]:
list(phone_numbers.values())[-1]

[('Billy', '652-2212')]

 &nbsp;

`.keys()` and `.values()`: are called `methods` on dictionaries

In [368]:
for group_type in list(phone_numbers.keys()):
        print("Group",group_type,":",sep=" ")
        for info in phone_numbers[group_type]:
             print("\t",info[0],info[1],sep=" ")

Group family :
	 mom 642-2322
	 dad 534-2311
Group friends :
	 Billy 652-2212


we cannot ensure ordering here of the groups

In [369]:
groups = list(phone_numbers.keys())
groups.sort()
for group_type in groups:
        print("Group",group_type,":",sep=" ")
        for info in phone_numbers[group_type]:
             print("\t",info[0],info[1],sep=" ")

Group family :
	 mom 642-2322
	 dad 534-2311
Group friends :
	 Billy 652-2212


`.items()` is a handy method,
returning key,value pairs with each iteration

In [370]:
for group_type, vals in phone_numbers.items():
        print("Group",group_type,":",sep=" ")
        for info in vals:
             print("\t",info[0],info[1],sep=" ")

Group family :
	 mom 642-2322
	 dad 534-2311
Group friends :
	 Billy 652-2212


Some examples of getting values:

In [371]:
phone_numbers['co-workers']

KeyError: 'co-workers'

In [372]:
'co-workers' in phone_numbers

False

In [373]:
print(phone_numbers.get('co-workers'))

None


In [374]:
phone_numbers.get('friends') == phone_numbers['friends']

True

Defaults in a `get`

In [375]:
print(phone_numbers.get('co-workers',"all alone"))

all alone


In [376]:
phone_numbers.get?

Signature: phone_numbers.get(key, default=None, /)
Docstring: Return the value for key if key is in the dictionary, else default.
Type:      builtin_function_or_method


 &nbsp;

 &nbsp;

#### setting values ####

you can edit the values of keys and also `.pop()` & `del` to remove certain keys

In [381]:
"BFFs" in phone_numbers.keys()

False

In [382]:
# add to the friends list
phone_numbers['friends'].append(("Marsha","232-1121"))
print(phone_numbers)

{'family': [('mom', '642-2322'), ('dad', '534-2311')], 'friends': [('Billy', '652-2212'), ('Marsha', '232-1121'), ('Marsha', '232-1121'), ('Marsha', '232-1121')]}


In [383]:
## billy's number changed
phone_numbers['friends'][0][1] = "532-1521"

TypeError: 'tuple' object does not support item assignment

In [384]:
phone_numbers['friends'][0] = ("Billy","532-1521")

In [385]:
## I lost all my friends preparing for this Python class
phone_numbers['friends'] = [] # sets this to an empty list

In [386]:
## remove the friends key altogether
print(phone_numbers.pop('friends'))

[]


In [ ]:
print(phone_numbers)

In [387]:
del phone_numbers['family']

In [388]:
print(phone_numbers)

{}


 &nbsp;

`.update()` method is very handy, like `.append()` for lists

In [389]:
phone_numbers.update({"friends": [("Billy's Brother, Bob", "532-1521")]})
print(phone_numbers)

{'friends': [("Billy's Brother, Bob", '532-1521')]}


&nbsp; 

### Casting Back and Forth ###

In [390]:
a = [1,2,3,("b",1),("b",1)]

In [ ]:
b = tuple(a) ; print(b)

In [391]:
print(list(b))

['m', 'a']


In [392]:
set(a)

{('b', 1), 1, 2, 3}

In [393]:
list(set("spam"))

['m', 's', 'a', 'p']

> casting only affects top-level structure, not the elements 

## List Comprehension ##

You can create lists "on the fly" by asking simple questions of other iterateable data structures

example: I want a list of all numbers from 0 - 100 whose lowest two bits are both one (e.g., 3, 7, ...) but is not divisible by 11

In [395]:
mylist = []
for num in range(101):
    if (num & 2) and (num & 1) and (num % 11 != 0.0):
        mylist.append(num)
print(mylist)

[3, 7, 15, 19, 23, 27, 31, 35, 39, 43, 47, 51, 59, 63, 67, 71, 75, 79, 83, 87, 91, 95]


In [396]:
mylist=[num for num in range(101) if (num & 2) \
        and (num & 1) and (num % 11 != 0.0)]
print(mylist)

[3, 7, 15, 19, 23, 27, 31, 35, 39, 43, 47, 51, 59, 63, 67, 71, 75, 79, 83, 87, 91, 95]


example: I want a list of all mesons whose masses are between 100 and 1000 MeV

In [398]:
particles = \
[{"name":"π+"  ,"mass": 139.57018}, {"name":"π0"  ,"mass": 134.9766}, 
 {"name":"η5"  ,"mass": 47.853}, {"name":"η′(958)","mass": 957.78}, 
 {"name":"ηc(1S)", "mass": 2980.5}, {"name": "ηb(1S)","mass": 9388.9}, 
 {"name":"K+",  "mass": 493.677}, {"name":"K0"  ,"mass": 497.614}, 
 {"name":"K0S" ,"mass":  497.614}, {"name":"K0L" ,"mass":  497.614},
 {"name":"D+"  ,"mass": 1869.62}, {"name":"D0"  ,"mass": 1864.84},
 {"name":"D+s" ,"mass":  1968.49}, {"name":"B+"  ,"mass": 5279.15},
 {"name":"B0"  ,"mass": 5279.5}, {"name":"B0s" ,"mass":  5366.3},
 {"name":"B+c" ,"mass":    6277}]

# data source: http://en.wikipedia.org/wiki/List_of_mesons

my_mesons = [ (x['name'],x['mass']) for \
    x in particles if x['mass'] <= 1000.0 and x['mass'] >= 100.0]

In [403]:
me_meson = [(x['name'], x['mass']) \
            for x in particles if x['mass'] >= 5000]

In [404]:
me_meson

[('ηb(1S)', 9388.9),
 ('B+', 5279.15),
 ('B0', 5279.5),
 ('B0s', 5366.3),
 ('B+c', 6277)]

In [405]:
# get the average
tot = 0.0
for x in my_mesons: tot += x[1]
print("The average meson mass in this range is " + str(tot/len(my_mesons)) \
    + " MeV/c^2.")

The average meson mass in this range is 459.83511142857145 MeV/c^2.


In [406]:
print("The average meson mass in this range is " + str(round(tot/len(my_mesons),2)) \
    + " MeV/c^2.")

The average meson mass in this range is 459.84 MeV/c^2.


In [407]:
my_mesons[0][0]

'π+'

In [408]:
bytes(my_mesons[0][0],encoding="utf-8")

b'\xcf\x80+'

 &nbsp;

## Breakout Session Work

Consider the following data (file: `airline.py`):

In [409]:
# %load airline.py
airports = {"DCA": "Washington, D.C.", "IAD": "Dulles", "LHR": "London-Heathrow", \
            "SVO": "Moscow", "CDA": "Chicago-Midway", "SBA": "Santa Barbara", "LAX": "Los Angeles",\
            "JFK": "New York City", "MIA": "Miami", "AUM": "Austin, Minnesota"}
            
# airline, number, heading to, gate, time (decimal hours) 
flights = [("Southwest",145,"DCA",1,6.00),("United",31,"IAD",1,7.1),("United",302,"LHR",5,6.5),\
           ("Aeroflot",34,"SVO",5,9.00),("Southwest",146,"CDA",1,9.60), ("United",46,"LAX",5,6.5),\
           ("Southwest",23,"SBA",6,12.5),("United",2,"LAX",10,12.5),("Southwest",59,"LAX",11,14.5),\
           ("American", 1,"JFK",12,11.3),("USAirways", 8,"MIA",20,13.1),("United",2032,"MIA",21,15.1),\
           ("SpamAir",1,"AUM",42,14.4)]


### 1. print out a schedule organized by airline:

<pre>
Flight          Destination          Gate   Time
--------------------------------------------------
Aeroflot 34    Moscow              	5   9.0
American 1     New York City       	12  11.3
Southwest 23   Santa Barbara       	6   12.5
Southwest 59   Los Angeles         	11  14.5
...
</pre>

### 2. print out a schedule organized by time

*hint: you'll need to do a manual sorting on the last element of each flight element, before beginning the printing loop*

<img id="embedLinkJPG" src="http://i3.cpcache.com/product/51620593/will_code_python_for_food_black_tshirt.jpg?color=Black&amp;height=460&amp;width=460&amp;qv=90" alt="Will Code Python For Food Black T-Shirt" width="460" height="460">